sylius_resource:
    resources:
        app.catalog_item:
            driver: doctrine/orm
            classes:
                model: App\Entity\CatalogItem
                form:  App\Form\Type\CatalogItemType
                repository: App\Repository\CatalogItemRepository
        app.catalog:
            driver: doctrine/orm
            classes:
                model: App\Entity\Catalog
                form:  App\Form\Type\CatalogType
                repository: App\Repository\CatalogRepository
        app.catalog_characteristic:
            driver: doctrine/orm
            classes:
                model: App\Entity\CatalogCharacteristic
                form: App\Form\Type\CatalogCharacteristicType
                repository: App\Repository\CatalogCharacteristicRepository
        app.catalog_item_characteristic:
            driver: doctrine/orm
            classes:
                model: App\Entity\CatalogItemCharacteristic
                form: App\Form\Type\CatalogItemCharacteristicType
                repository: App\Repository\CatalogItemCharacteristicRepository
        app.catalog_group:
            driver: doctrine/orm
            classes:
                model: App\Entity\CatalogGroup
                form: App\Form\Type\CatalogGroupType
                repository: App\Repository\CatalogGroupRepository
        app.catalog_item_image:
            driver: doctrine/orm
            classes:
                model: App\Entity\CatalogItemImage
                form: App\Form\Type\CatalogItemImageType
                repository: App\Repository\CatalogItemImageRepository
        app.feedback_from_map:
            driver: doctrine/orm
            classes:
                model: App\Entity\FeedbackFromMap
                form: App\Form\Type\FeedbackFromMapType
                repository: App\Repository\FeedbackFromMapRepository
        app.user:
            driver: doctrine/orm
            classes:
                model: App\Entity\User
                form: App\Form\Type\UserType
                repository: App\Repository\UserRepository
        app.cart:
            driver: doctrine/orm
            classes:
                model: App\Entity\Cart
                form: App\Form\Type\CartType
                repository: App\Repository\CartRepository

        app.compare:
            driver: doctrine/orm
            classes:
                model: App\Entity\Compare
                form: App\Form\Type\CompareType
                repository: App\Repository\CompareRepository

        app.favorite:
            driver: doctrine/orm
            classes:
                model: App\Entity\Favorite
                form: App\Form\Type\FavoriteType
                repository: App\Repository\FavoriteRepository

        app.user_token:
            driver: doctrine/orm
            classes:
                model: App\Entity\UserToken
                repository: App\Repository\UserTokenRepository

        app.service_group:
            driver: doctrine/orm
            classes:
                model: App\Entity\ServiceGroup
                form: App\Form\Type\ServiceGroupType
                repository: App\Repository\ServiceGroupRepository
        app.service:
            driver: doctrine/orm
            classes:
                model: App\Entity\Service
                form: App\Form\Type\ServiceType
                repository: App\Repository\ServiceRepository
